# Generated by Django 3.2.6 on 2022-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaksinasi',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
