# Generated by Django 3.2.6 on 2022-02-08 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20220208_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpdesk',
            fields=[
                ('help_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('help_status', models.CharField(max_length=30)),
                ('email_subject', models.CharField(max_length=50)),
                ('email_content', models.CharField(max_length=500)),
                ('date_created', models.DateField()),
                ('user_email', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='email_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
