# Generated by Django 3.2.6 on 2022-02-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_helpdesk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helpdesk',
        ),
    ]
