# Generated by Django 3.2.6 on 2022-02-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(default='bgdefault.jpeg', upload_to='bg_pics'),
        ),
    ]
