# Generated by Django 3.2.6 on 2022-02-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_helpdesk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='helpdesk',
        ),
    ]
