# Generated by Django 3.2.6 on 2022-02-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_helpdesk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdesk',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
