# Generated by Django 3.2.6 on 2022-02-09 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_alter_helpdesk_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdesk',
            name='user_email',
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='author_help',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
