# Generated by Django 3.1.14 on 2022-02-09 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20220209_0853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helpdesk',
        ),
    ]
