# Generated by Django 3.1.14 on 2022-02-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_delete_helpdesk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpdesk',
            fields=[
                ('help_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('help_status', models.CharField(max_length=30)),
                ('email_subject', models.CharField(max_length=50)),
                ('email_content', models.CharField(max_length=500)),
                ('date_created', models.DateField(auto_now=True)),
                ('email_user', models.EmailField(max_length=254)),
            ],
        ),
    ]
